# Generated by Django 5.2.6 on 2025-09-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='provincia',
        ),
    ]
