# Generated by Django 5.2.6 on 2025-09-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='carritos_usuarios',
        ),
        migrations.AlterModelTable(
            name='carritoproducto',
            table='carritos_productos',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias_productos',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos_usuarios',
        ),
        migrations.AlterModelTable(
            name='pedidoproducto',
            table='pedidos_productos',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfiles_usuarios',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='productoimagen',
            table='imagenes_productos',
        ),
    ]
