# Generated by Django 5.2.6 on 2025-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pedido_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
