# Generated by Django 5.2.6 on 2025-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedidoproducto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
