# Generated by Django 5.2.6 on 2025-09-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/productos/'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/productos/'),
        ),
    ]
